services:
  # The Backend
  - type: web
    name: my-api
    env: bun
    buildCommand: bun install
    startCommand: bun run start
    envVars:
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false # You will enter this in the dashboard manually
